/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for defining interactive choose-your-own-adventure story nodes
 */
export type FightingFantasyAdventureStoryData = {
  /**
   * Unique identifier for the story node
   */
  id: string;
  /**
   * Title displayed at the top of the story node
   */
  title: string;
  /**
   * Type of story node governing logic or display
   */
  node_type: "start" | "decision" | "scene_start" | "end" | "adventure_success" | "narrative" | "combat" | "puzzle";
  /**
   * If true, this node is an explicit checkpoint. The player's visit is persisted and offered as a return point when an end node is reached.
   */
  checkpoint?: boolean;
  /**
   * Main descriptive text for the story node
   */
  narrativeText: string;
  /**
   * Sound effect played when entering this node (or 'none')
   */
  entry_foley?: string;
  /**
   * Background music track for this node (or 'none')
   */
  music?: string;
  /**
   * Ambient sound effects for this node (or 'none')
   */
  sounds?: string;
  /**
   * List of activities or challenges in this node
   */
  activities?: string[];
  /**
   * Available choices for the player in this node
   */
  choices: {
    choiceText: string;
    choiceResponseConstraint: string;
    nextNode: string;
  }[];
}[];
